export enum ChannelType {
  ZL_MESSAGE = 'ZL_MESSAGE',
  WS_MESSAGE = 'WS_MESSAGE',
  FB_MESSAGE = 'FB_MESSAGE',
  VB_MESSAGE = 'VB_MESSAGE',
  FB_PAGE = 'FB_PAGE',
  ZL_PAGE = 'ZL_PAGE',
  LIVE_CHAT = 'LIVE_CHAT',
}
