export enum NotifyEventType {
  NEW_CONVERSATION = 'NEW_CONVERSATION',
  NEW_MESSAGE_NO_READY = 'NEW_CONVERSATION_NO_READY',
  PICK_CONVERSATION = 'PICK_CONVERSATION',
  CLOSE_CONVERSATION = 'CLOSE_CONVERSATION',
  RATE_CONVERSATION = 'RATE_CONVERSATION',
  NEW_MESSAGE = 'NEW_MESSAGE',
  MESSAGE_TRANSFERED = 'MESSAGE_TRANSFERED',
  CUSTOMER_LEFT = 'CUSTOMER_LEFT',
  CUSTOMER_JOIN = 'CUSTOMER_JOIN',
  ASSIGN_CONVERSATION = 'ASSIGN_CONVERSATION',
  UNASSIGN_CONVERSATION = 'UNASSIGN_CONVERSATION',
  TRANSFER_CONVERSATION = 'TRANSFER_CONVERSATION',
  JOIN_CONVERSATION = 'JOIN_CONVERSATION',
  LEAVE_CONVERSATION = 'LEAVE_CONVERSATION',
  MESSAGE_REFRESH_FRONTEND = 'MESSAGE_REFRESH_FRONTEND'
}
