export enum NotifyEventType {
  NEW_CONVERSATION = 'NEW_CONVERSATION',
  PICK_CONVERSATION = 'PICK_CONVERSATION',
  CLOSE_CONVERSATION = 'CLOSE_CONVERSATION',
  RATE_CONVERSATION = 'RATE_CONVERSATION',
  NEW_MESSAGE = 'NEW_MESSAGE',
  MESSAGE_TRANSFERED = 'MESSAGE_TRANSFERED',
  CUSTOMER_LEFT = 'CUSTOMER_LEFT',
  CUSTOMER_JOIN = 'CUSTOMER_JOIN',
}
